#!/usr/bin/env bash
################################################################################
# This is property of eXtremeSHOK.com
# You are free to use, modify and distribute, however you may not remove this notice.
# Copyright (c) Adrian Jon Kriel :: admin@extremeshok.com
################################################################################
#
# Wrapped function for apt-get update && apt-get install && apt-get clean
# will automatically retry a failed apt-install where the package failes to download
#
################################################################################
# Retry install packages
max_retries=12
current_retries=0
sleep_between_retries=5

apt-get update

# save error message (stderr) to error and display output (stdout)
until { error=$(apt-get -q -y -o Dpkg::Options::="--force-confmiss" -o DPkg::Options::="--force-confold" -o DPkg::Options::="--force-confdef" install --no-install-recommends "$@" 2>&1 1>&$out); } {out}>&1 ; do
  ret="$?"
  if [[ "$error" == *"Unable to locate package"* ]] ; then
    echo "${error/E: /}"
    exit "$ret"
  fi
  current_retries=$((current_retries + 1))
  if [ $current_retries -gt $max_retries ] ; then
    echo "ERROR: max retries of ${max_retries} reached"
    exit "1"
  fi
  echo "== Install of package/s failed, retrying ${current_retries}/${max_retries} =="
  sleep "$sleep_between_retries"
done

apt-get clean
